### ISSUE TITLE
빌드에러 질문 - entry point (_main) undefined. for architecture arm64

### ISSUE THREAD

**Issue by thisisthewa2** [Swift-Coding-Club/ToolCook#9]
<img width="1440" alt="스크린샷 2023-03-04 오후 6 03 51" src="https://user-images.githubusercontent.com/119280160/222887532-b3c5cf43-ce30-4075-bdea-d5bdbef8e1d2.png">

제 코드를 전혀 추가하지 않고 main의 최신 코드를 풀받아도 빌드하려면 이런 에러가 생깁니다.
PasterTimerApp 파일에는 @main 이 잘 써져 있는데 왜 이런 문제가 생기는지 잘 모르겠습니다. 관련된 파일을 전부 삭제하고 새로 풀 받거나 xcode나 맥 자체를 재부팅해도 효과가 없습니다.
검색해보니 AppDelegate 파일에 @UIApplicationMain을 추가하는 방법을 주로 추천하는데, swift ui 프로젝트인지라 억지로 appdelegate파일을 만드는 것이 꺼려집니다. 혹시 해결 방법을 아신다면 댓글로 꼭 알려주세요. 감사합니다.

**Comment by kangddong** [comment]
확인해볼게요

**Comment by kangddong** [comment]
entry point (_ main)이 지정되지않았다는 것은
PastaTimerApp.swift의 @main 찾지 못했을 때 나오는 에러인데요
![image](https://user-images.githubusercontent.com/50406861/222904410-c381c722-06dc-479c-9779-bb8d017903f4.png)
하지만 @main 선언이 잘되어있길래 어떤 부분이 문제일지 다시 생각해보았는데

파일 인스펙터 창의 Target Membership 에서 PastaTimer에 체크가 되어있지않은 모습을 발견했어요

![image](https://user-images.githubusercontent.com/50406861/222904362-803ee8fc-f97d-435d-bc87-0c2eb3f7d3b4.png)

다른 파일들도 마찬가지라서 Target을 PastaTimer로 변경하니 빌드 성공하였어요 
픽스해서 다시 푸시 해놓겠습니다 
확인해주셔서 감사해요 🤗

**Comment by thisisthewa2** [comment]
헉 그런 이유에서였군요 앞으론 타깃을 잘 확인해야겠습니다. 감사합니다!

**Comment by kangddong** [comment]
해결되셨으면 클로즈 부탁드려용 !
